# Generated by Django 4.2.11 on 2024-05-17 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('minimumPercentageFor5', models.IntegerField(blank=True, null=True, verbose_name='% для 5')),
                ('minimumPercentageFor4', models.IntegerField(blank=True, null=True, verbose_name='% для 4')),
                ('minimumPercentageFor3', models.IntegerField(blank=True, null=True, verbose_name='% для 3')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Буква класса')),
                ('year', models.IntegerField(verbose_name='Год набора')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('skill', models.CharField(blank=True, max_length=255, null=True, verbose_name='Проверяемый навык')),
                ('maxPoint', models.IntegerField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('attestation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.attestation', verbose_name='Работа')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефонный номер')),
                ('classes', models.ManyToManyField(blank=True, to='MainApp.schoolclass', verbose_name='Классы')),
                ('subject', models.ManyToManyField(blank=True, to='MainApp.subject', verbose_name='Предметы')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='Баллы')),
                ('task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.task', verbose_name='Задание')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('results', models.ManyToManyField(blank=True, to='MainApp.taskresult', verbose_name='Результаты заданий')),
                ('schoolClass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.schoolclass', verbose_name='Класс')),
            ],
        ),
        migrations.AddField(
            model_name='attestation',
            name='schoolClass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.schoolclass', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.teacher', verbose_name='Учитель'),
        ),
    ]
