# Generated by Django 5.0.3 on 2024-03-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attestation',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='schoolClass',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolClass',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectlist',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectlist',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='task',
        ),
        migrations.DeleteModel(
            name='Attestation',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassList',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectList',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
