# Generated by Django 5.0.3 on 2024-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='theme',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='skill',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fullName',
            field=models.CharField(max_length=255),
        ),
    ]
