# Generated by Django 5.0.3 on 2024-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_rename_class_schoolclass_teacher_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='MainApp.subject'),
        ),
        migrations.DeleteModel(
            name='SubjectList',
        ),
    ]
