# Generated by Django 5.0.3 on 2024-03-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_teacher_subject_delete_subjectlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attestation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolClass',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='task',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attestation',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskResult',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
