# Generated by Django 5.0.3 on 2024-03-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='taskResults',
        ),
        migrations.AddField(
            model_name='student',
            name='taskResults',
            field=models.ManyToManyField(to='MainApp.taskresult'),
        ),
    ]
