# Generated by Django 5.0.3 on 2024-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_remove_taskresult_student_student_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
