# Generated by Django 5.0.3 on 2024-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_alter_student_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attestation',
        ),
        migrations.AddField(
            model_name='attestation',
            name='task',
            field=models.ManyToManyField(to='MainApp.task'),
        ),
    ]
