# Generated by Django 5.0.3 on 2024-03-24 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_remove_task_attestation_attestation_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='attestation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.attestation'),
            preserve_default=False,
        ),
    ]
