# Generated by Django 4.2.11 on 2024-03-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_remove_task_attestation_attestation_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='task',
            field=models.ManyToManyField(blank=True, null=True, to='MainApp.task', verbose_name='Задания'),
        ),
    ]
