# Generated by Django 4.2.11 on 2024-03-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_alter_attestation_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='attestation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.attestation', verbose_name='Работа'),
        ),
    ]
