# Generated by Django 5.0.3 on 2024-04-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_remove_task_attestation_attestation_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='attestation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MainApp.attestation', verbose_name='Работа'),
        ),
    ]
