# Generated by Django 5.0.3 on 2024-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0030_remove_attestation_task_task_attestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, to='MainApp.schoolclass', verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, to='MainApp.subject', verbose_name='Предметы'),
        ),
    ]
